name: Releases

#on: 
 # push:
  #  tags:
   # - 'v1.0.1'
    
on: create

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "banking/build/libbanking.a"
        token: ${{ secrets.GITHUB_TOKEN }}
