name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag_name: ${{ github.ref }}
        artifacts: "banking/build/libbanking.a"
        token: ${{ secrets.GITHUB_TOKEN }}
